apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobzilla
spec:
  selector: 
    matchLabels:
      app: jobzilla
  template:
    metadata:
      labels:
        app: jobzilla
    spec:
      containers:
      - name: jobzilla
        image: magalixcorp/jobzilla
        ports:
        - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: jobzilla-svc
spec:
  selector:
    app: jobzilla
  ports:
  - name: http
    port: 80
    targetPort: 9091