apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
spec:
  selector: 
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
      - name: manager
        image: magalixcorp/manager
        ports:
        - containerPort: 80
        env:
        - name: sources_url
          value: http://sources-svc/
        - name: feeds_url
          value: http://feeds-svc/
---
apiVersion: v1
kind: Service
metadata:
  name: manager-svc
spec:
  selector:
    app: manager
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 32001