apiVersion: apps/v1
kind: Deployment
metadata:
  name: sources
spec:
  selector: 
    matchLabels:
      app: sources
  template:
    metadata:
      labels:
        app: sources
    spec:
      containers:
      - name: sources
        image: magalixcorp/sources
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: sources-svc
spec:
  selector:
    app: sources
  ports:
  - name: http
    port: 80
    targetPort: 8081